#!/usr/bin/env bash
# World wide web

get_domain_info()
{
    subdomain=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4,$5}')
    record=$(echo $subdomain | cut -d " " -f 1)
    ip=$(echo $subdomain | cut -d " " -f 2)
    echo "The subdomain $2 is a $record record and points to $ip"
}
if [ $# -eq 1 ]
then
    get_domain_info "$1" "www"
    get_domain_info "$1" "lb-01"
    get_domain_info "$1" "web-01"
    get_domain_info "$1" "web-02"
elif [ $# -eq 2 ]
then
    get_domain_info "$1" "$2"
fi
