#!/usr/bin/env bash
#groups visitors by IP and HTTP status code, sort, and displays unique data and number of occurences

awk '{count[$1]++} END {for(k in count) print "\t" count[k], k, $9}' apache-access.log | sort -u -nr