#!/usr/bin/env bash
#Display 'Best School' 10 times with `while` loop but the 9th loop should print `Hi` 

i=1
while [ $i -le 10 ]
 do
    if [[ $i -eq 9 ]]
    then
        echo "Hi"
    else
        echo 'Best School'
    fi
    i=$((i+1))
done